name: publish-slides
on: [push]

jobs:
  built-slides:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: build
        - run: |
            cd slides/src
            curl -LO https://raw.githubusercontent.com/arnehilmann/markdeck/master/markdeck
            chmod a+x markdeck
            pwd
            ls
            ./markdeck once