name: publish-slides
on: [push]

jobs:
  built-slides:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd slides/src
        - run: curl -LO https://raw.githubusercontent.com/arnehilmann/markdeck/master/markdeck
        - run: chmod a+x markdeck
        - run: pwd
        - run: ls
        - run: ./markdeck once