name: publish-slides
on: [push]

jobs:
  built-slides:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: build
          run: |
            cd slides/src
            curl -LO https://raw.githubusercontent.com/arnehilmann/markdeck/master/markdeck
            chmod a+x markdeck
            pwd
            ls
            ./markdeck once
        
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@3.6.2
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: slides/src/deck # The folder the action should deploy.
            CLEAN: true # Automatically remove deleted files from the deploy branch